### PR TITLE
Update rust toolchain to `+1.51.0`

### PR DESCRIPTION
**Pull request by Silverhorn27**
* Update dependencies
  - `libc` v0.2.68 to v0.2.103
  - `failure` v0.1.7 to v0.1.8
  - `failure_derive` v0.1.7 to v.0.1.8
  - `bindgen` v0.3.0 to v0.3.1

* Update toolchain to `+1.51.0`
  - Fixed `clippy` lints and warns
  There was removed a mess of lifetimes and suspended clippy
  `missing_safety_doc` lint.

* Formate code by `rustfmt`

### CODE REVIEW

**Comment by Silverhorn27** [comment]
cc @mmstick, @jackpot51. Please, review this PR.

**Comment by jackpot51** [comment]
We generally cannot update the toolchain beyond that used in most Linux distributions. Our current preferred version is `1.51.0`

**Comment by Silverhorn27** [comment]
@jackpot51 I remade my PR to use `+1.51.0` rust-toolchain. There are present fixes also for `+1.55.0`. Everything was checked by `clippy --workspace --all-targets --all-features`. Could you please review it again?

**Comment by Silverhorn27** [comment]
I think we can wait for release of `libparted-sys` to don't use particular revision. What do you think about it?

**Comment by jackpot51** [comment]
I agree

**Comment by Silverhorn27** [comment]
I updated PR and I'll be glad if after merge this you'll make a new release. Thanks :)

**Comment by Silverhorn27** [comment]
@mmstick, @jackpot51 Could you look at this PR again?

**Review by jackpot51 — APPROVED** [review]

**Comment by Silverhorn27** [comment]
@jackpot51 may you know who can review this PR too?

**Comment by Silverhorn27** [comment]
@mmstick Thank you :+1:

**Comment by Silverhorn27** [comment]
@jackpot51 could you please release a new version of crate?

**Comment by jackpot51** [comment]
Released as libparted 0.1.5

**Comment by Silverhorn27** [comment]
Thank you a lot :)

**Pull request merged**
